In [85]:
import sys
print(sys.executable)

c:\Users\khines\AppData\Local\Programs\Python\Python314\python.exe

In [86]:
import pandas as pd
pd.read_csv("graduates.csv")

,Year,Demographics.Total,Education.Major,Salaries.Highest,Salaries.Lowest,Salaries.Mean,Salaries.Median,Salaries.Quantity,Salaries.Standard Deviation,Demographics.Ethnicity.Asians,Demographics.Ethnicity.Minorities,Demographics.Ethnicity.Whites,Demographics.Gender.Females,Demographics.Gender.Males,Education.Degrees.Bachelors,Education.Degrees.Doctorates,Education.Degrees.Masters,Education.Degrees.Professionals,Employment.Employer Type.Business/Industry,Employment.Employer Type.Educational Institution,Employment.Employer Type.Government,Employment.Reason Working Outside Field.Career Change,Employment.Reason Working Outside Field.Family-related,Employment.Reason Working Outside Field.Job Location,Employment.Reason Working Outside Field.No Job Available,Employment.Reason Working Outside Field.Other,Employment.Reason Working Outside Field.Pay/Promotion,Employment.Reason Working Outside Field.Working Conditions,Employment.Reason for Not Working.Family,Employment.Reason for Not Working.Layoff,Employment.Reason for Not Working.No Job Available,Employment.Reason for Not Working.No need/want,Employment.Reason for Not Working.Student,Employment.Status.Employed,Employment.Status.Not in Labor Force,Employment.Status.Unemployed,Employment.Work Activity.Accounting/Finance/Contracts,Employment.Work Activity.Applied Research,Employment.Work Activity.Basic Research,Employment.Work Activity.Computer Applications,Employment.Work Activity.Design,Employment.Work Activity.Development,Employment.Work Activity.Human Resources,Employment.Work Activity.Managing/Supervising People/Projects,Employment.Work Activity.Other,Employment.Work Activity.Productions/Operations/Maintenance,Employment.Work Activity.Professional Service,Employment.Work Activity.Qualitity/Productivity Management,"Employment.Work Activity.Sales, Purchasing, Marketing",Employment.Work Activity.Teaching
0,1993,1295598,Biological Sciences,999999,0,160585.73,51000,13432,297818.25,84495,115016,1094775,551695,743903,671374,90543,248813,284869,669270,300468,121117,98112,65619,90842,76598,24821,111962,100886,45962,7457,14976,30989,51891,1090855,181940,22803,793888,341238,224277,297235,118772,191867,365049,539430,99749,103385,506252,269042,215169,381908
1,1993,211875,Chemical Engineering,999999,9000,126176.52,56000,3375,245705.77,27531,11278,173067,32205,179670,125883,17024,61809,7159,150692,10640,12879,11081,4968,6803,7164,3836,8649,6025,3275,1879,3168,4572,2154,174210,34018,3647,95346,65810,25328,67868,82344,76108,59299,102248,16361,30480,24690,63895,44780,17718
2,1993,507616,Chemistry,999999,8000,148872.00,60000,7834,276000.33,49984,35181,421911,135802,371814,243247,83078,101591,79700,279775,88760,38050,36072,18553,22098,19280,12778,31284,24843,9326,5705,7902,13743,9453,406585,89594,11437,240410,170327,95221,126471,81772,123256,121783,208278,35007,40898,129716,114801,78059,104191
3,1993,336366,Civil Engineering,999999,10000,129070.55,50000,4035,259543.49,37295,17421,281442,21022,315344,235237,9884,87754,3490,186818,13541,87878,12002,5402,8462,6616,5802,11440,9580,1684,3728,5578,3997,2477,288237,39966,8163,197407,68530,34892,123613,133430,62031,108338,203035,37940,28639,70727,116758,73133,26892
4,1993,1070111,Computer Science and Math,999999,0,134299.53,49000,9996,269323.82,83826,98047,887476,386111,684000,746586,46308,258567,18650,665249,183217,89658,59302,34499,56946,50406,24238,64066,56745,33796,13946,16227,23997,10210,938124,103062,28925,484716,239183,131348,640201,251941,200490,287405,439446,62482,73411,126083,223467,168404,234507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,2015,1176525,Sociology,1223166,0,58871.70,50000,1798,62083.18,59244,305810,811471,801803,374722,747039,28534,356024,44928,489371,208299,111305,79521,53514,131176,79267,17042,163408,147053,78620,10409,23291,71675,12888,808975,337378,30172,213336,152147,144029,75332,85782,151538,261143,415552,204818,72050,342903,183692,345302,301924
513,2015,55738,Statistics,1038725,0,99210.87,88000,157,90534.66,16211,5723,33805,36335,19403,32158,3741,18734,1106,32799,3449,4517,1263,2903,5563,3677,0,3226,3104,12134,567,0,1500,53,40765,14353,620,18149,18899,9908,17036,13908,11798,8419,19960,3437,5489,12803,7736,10741,6290
514,2015,169991,"Zoology, General",1223166,0,86957.98,60000,317,124675.05,17563,12856,139571,72648,97343,58806,26546,39510,45129,75944,27630,21835,18574,15188,17235,5506,2576,11701,26526,4492,850,1680,19283,2322,125409,42880,1703,27241,41914,28174,9366,15366,30180,29873,60016,29924,24622,57404,30979,35810,56660
515,2015,0,Management & Administration,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
516,2015,0,Political and related sciences,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [87]:
# IMPORTS CSV 

df= pd.read_csv("graduates.csv")
df.head(5)

,Year,Demographics.Total,Education.Major,Salaries.Highest,Salaries.Lowest,Salaries.Mean,Salaries.Median,Salaries.Quantity,Salaries.Standard Deviation,Demographics.Ethnicity.Asians,Demographics.Ethnicity.Minorities,Demographics.Ethnicity.Whites,Demographics.Gender.Females,Demographics.Gender.Males,Education.Degrees.Bachelors,Education.Degrees.Doctorates,Education.Degrees.Masters,Education.Degrees.Professionals,Employment.Employer Type.Business/Industry,Employment.Employer Type.Educational Institution,Employment.Employer Type.Government,Employment.Reason Working Outside Field.Career Change,Employment.Reason Working Outside Field.Family-related,Employment.Reason Working Outside Field.Job Location,Employment.Reason Working Outside Field.No Job Available,Employment.Reason Working Outside Field.Other,Employment.Reason Working Outside Field.Pay/Promotion,Employment.Reason Working Outside Field.Working Conditions,Employment.Reason for Not Working.Family,Employment.Reason for Not Working.Layoff,Employment.Reason for Not Working.No Job Available,Employment.Reason for Not Working.No need/want,Employment.Reason for Not Working.Student,Employment.Status.Employed,Employment.Status.Not in Labor Force,Employment.Status.Unemployed,Employment.Work Activity.Accounting/Finance/Contracts,Employment.Work Activity.Applied Research,Employment.Work Activity.Basic Research,Employment.Work Activity.Computer Applications,Employment.Work Activity.Design,Employment.Work Activity.Development,Employment.Work Activity.Human Resources,Employment.Work Activity.Managing/Supervising People/Projects,Employment.Work Activity.Other,Employment.Work Activity.Productions/Operations/Maintenance,Employment.Work Activity.Professional Service,Employment.Work Activity.Qualitity/Productivity Management,"Employment.Work Activity.Sales, Purchasing, Marketing",Employment.Work Activity.Teaching
0,1993,1295598,Biological Sciences,999999,0,160585.73,51000,13432,297818.25,84495,115016,1094775,551695,743903,671374,90543,248813,284869,669270,300468,121117,98112,65619,90842,76598,24821,111962,100886,45962,7457,14976,30989,51891,1090855,181940,22803,793888,341238,224277,297235,118772,191867,365049,539430,99749,103385,506252,269042,215169,381908
1,1993,211875,Chemical Engineering,999999,9000,126176.52,56000,3375,245705.77,27531,11278,173067,32205,179670,125883,17024,61809,7159,150692,10640,12879,11081,4968,6803,7164,3836,8649,6025,3275,1879,3168,4572,2154,174210,34018,3647,95346,65810,25328,67868,82344,76108,59299,102248,16361,30480,24690,63895,44780,17718
2,1993,507616,Chemistry,999999,8000,148872.00,60000,7834,276000.33,49984,35181,421911,135802,371814,243247,83078,101591,79700,279775,88760,38050,36072,18553,22098,19280,12778,31284,24843,9326,5705,7902,13743,9453,406585,89594,11437,240410,170327,95221,126471,81772,123256,121783,208278,35007,40898,129716,114801,78059,104191
3,1993,336366,Civil Engineering,999999,10000,129070.55,50000,4035,259543.49,37295,17421,281442,21022,315344,235237,9884,87754,3490,186818,13541,87878,12002,5402,8462,6616,5802,11440,9580,1684,3728,5578,3997,2477,288237,39966,8163,197407,68530,34892,123613,133430,62031,108338,203035,37940,28639,70727,116758,73133,26892
4,1993,1070111,Computer Science and Math,999999,0,134299.53,49000,9996,269323.82,83826,98047,887476,386111,684000,746586,46308,258567,18650,665249,183217,89658,59302,34499,56946,50406,24238,64066,56745,33796,13946,16227,23997,10210,938124,103062,28925,484716,239183,131348,640201,251941,200490,287405,439446,62482,73411,126083,223467,168404,234507

In [88]:
# Dataset Size 
df.shape

(517, 50)

In [89]:
# Columss in Dataset 
df.columns

Index(['Year', 'Demographics.Total', 'Education.Major', 'Salaries.Highest',
       'Salaries.Lowest', 'Salaries.Mean', 'Salaries.Median',
       'Salaries.Quantity', 'Salaries.Standard Deviation',
       'Demographics.Ethnicity.Asians', 'Demographics.Ethnicity.Minorities',
       'Demographics.Ethnicity.Whites', 'Demographics.Gender.Females',
       'Demographics.Gender.Males', 'Education.Degrees.Bachelors',
       'Education.Degrees.Doctorates', 'Education.Degrees.Masters',
       'Education.Degrees.Professionals',
       'Employment.Employer Type.Business/Industry',
       'Employment.Employer Type.Educational Institution',
       'Employment.Employer Type.Government',
       'Employment.Reason Working Outside Field.Career Change',
       'Employment.Reason Working Outside Field.Family-related',
       'Employment.Reason Working Outside Field.Job Location',
       'Employment.Reason Working Outside Field.No Job Available',
       'Employment.Reason Working Outside Field.Other',
       'Employment.Reason Working Outside Field.Pay/Promotion',
       'Employment.Reason Working Outside Field.Working Conditions',
       'Employment.Reason for Not Working.Family',
       'Employment.Reason for Not Working.Layoff',
       'Employment.Reason for Not Working.No Job Available',
       'Employment.Reason for Not Working.No need/want',
       'Employment.Reason for Not Working.Student',
       'Employment.Status.Employed', 'Employment.Status.Not in Labor Force',
       'Employment.Status.Unemployed',
       'Employment.Work Activity.Accounting/Finance/Contracts',
       'Employment.Work Activity.Applied Research',
       'Employment.Work Activity.Basic Research',
       'Employment.Work Activity.Computer Applications',
       'Employment.Work Activity.Design',
       'Employment.Work Activity.Development',
       'Employment.Work Activity.Human Resources',
       'Employment.Work Activity.Managing/Supervising People/Projects',
       'Employment.Work Activity.Other',
       'Employment.Work Activity.Productions/Operations/Maintenance',
       'Employment.Work Activity.Professional Service',
       'Employment.Work Activity.Qualitity/Productivity Management',
       'Employment.Work Activity.Sales, Purchasing, Marketing',
       'Employment.Work Activity.Teaching'],
      dtype='str')

In [90]:
# Datset Information 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 50 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Year                                                           517 non-null    int64
 1   Demographics.Total                                             517 non-null    int64
 2   Education.Major                                                517 non-null    str
 3   Salaries.Highest                                               517 non-null    int64
 4   Salaries.Lowest                                                517 non-null    int64
 5   Salaries.Mean                                                  517 non-null    float64
 6   Salaries.Median                                                517 non-null    int64
 7   Salaries.Quantity                                              517 non-null    int64
 8   Salaries.Standard Deviation                                    517 non-null    float64
 9   Demographics.Ethnicity.Asians                                  517 non-null    int64
 10  Demographics.Ethnicity.Minorities                              517 non-null    int64
 11  Demographics.Ethnicity.Whites                                  517 non-null    int64
 12  Demographics.Gender.Females                                    517 non-null    int64
 13  Demographics.Gender.Males                                      517 non-null    int64
 14  Education.Degrees.Bachelors                                    517 non-null    int64
 15  Education.Degrees.Doctorates                                   517 non-null    int64
 16  Education.Degrees.Masters                                      517 non-null    int64
 17  Education.Degrees.Professionals                                517 non-null    int64
 18  Employment.Employer Type.Business/Industry                     517 non-null    int64
 19  Employment.Employer Type.Educational Institution               517 non-null    int64
 20  Employment.Employer Type.Government                            517 non-null    int64
 21  Employment.Reason Working Outside Field.Career Change          517 non-null    int64
 22  Employment.Reason Working Outside Field.Family-related         517 non-null    int64
 23  Employment.Reason Working Outside Field.Job Location           517 non-null    int64
 24  Employment.Reason Working Outside Field.No Job Available       517 non-null    int64
 25  Employment.Reason Working Outside Field.Other                  517 non-null    int64
 26  Employment.Reason Working Outside Field.Pay/Promotion          517 non-null    int64
 27  Employment.Reason Working Outside Field.Working Conditions     517 non-null    int64
 28  Employment.Reason for Not Working.Family                       517 non-null    int64
 29  Employment.Reason for Not Working.Layoff                       517 non-null    int64
 30  Employment.Reason for Not Working.No Job Available             517 non-null    int64
 31  Employment.Reason for Not Working.No need/want                 517 non-null    int64
 32  Employment.Reason for Not Working.Student                      517 non-null    int64
 33  Employment.Status.Employed                                     517 non-null    int64
 34  Employment.Status.Not in Labor Force                           517 non-null    int64
 35  Employment.Status.Unemployed                                   517 non-null    int64
 36  Employment.Work Activity.Accounting/Finance/Contracts          517 non-null    int64
 37  Employment.Work Activity.Applied Research                      517 non-null    int64
 38  Employment.Work Activity.Basic Research                        517 non-null    int64
 39  Employment.Work Activity.Computer Applications                 517 non-null    int64
 40  Employment.Work Activity.Design                                517 non-null    int64
 41  Employment.Work Activity.Development                           517 non-null    int64
 42  Employment.Work Activity.Human Resources                       517 non-null    int64
 43  Employment.Work Activity.Managing/Supervising People/Projects  517 non-null    int64
 44  Employment.Work Activity.Other                                 517 non-null    int64
 45  Employment.Work Activity.Productions/Operations/Maintenance    517 non-null    int64
 46  Employment.Work Activity.Professional Service                  517 non-null    int64
 47  Employment.Work Activity.Qualitity/Productivity Management     517 non-null    int64
 48  Employment.Work Activity.Sales, Purchasing, Marketing          517 non-null    int64
 49  Employment.Work Activity.Teaching                              517 non-null    int64
dtypes: float64(2), int64(47), str(1)
memory usage: 202.1 KB

In [91]:
df.describe()

,Year,Demographics.Total,Salaries.Highest,Salaries.Lowest,Salaries.Mean,Salaries.Median,Salaries.Quantity,Salaries.Standard Deviation,Demographics.Ethnicity.Asians,Demographics.Ethnicity.Minorities,Demographics.Ethnicity.Whites,Demographics.Gender.Females,Demographics.Gender.Males,Education.Degrees.Bachelors,Education.Degrees.Doctorates,Education.Degrees.Masters,Education.Degrees.Professionals,Employment.Employer Type.Business/Industry,Employment.Employer Type.Educational Institution,Employment.Employer Type.Government,Employment.Reason Working Outside Field.Career Change,Employment.Reason Working Outside Field.Family-related,Employment.Reason Working Outside Field.Job Location,Employment.Reason Working Outside Field.No Job Available,Employment.Reason Working Outside Field.Other,Employment.Reason Working Outside Field.Pay/Promotion,Employment.Reason Working Outside Field.Working Conditions,Employment.Reason for Not Working.Family,Employment.Reason for Not Working.Layoff,Employment.Reason for Not Working.No Job Available,Employment.Reason for Not Working.No need/want,Employment.Reason for Not Working.Student,Employment.Status.Employed,Employment.Status.Not in Labor Force,Employment.Status.Unemployed,Employment.Work Activity.Accounting/Finance/Contracts,Employment.Work Activity.Applied Research,Employment.Work Activity.Basic Research,Employment.Work Activity.Computer Applications,Employment.Work Activity.Design,Employment.Work Activity.Development,Employment.Work Activity.Human Resources,Employment.Work Activity.Managing/Supervising People/Projects,Employment.Work Activity.Other,Employment.Work Activity.Productions/Operations/Maintenance,Employment.Work Activity.Professional Service,Employment.Work Activity.Qualitity/Productivity Management,"Employment.Work Activity.Sales, Purchasing, Marketing",Employment.Work Activity.Teaching
count,517.000000,5.170000e+02,5.170000e+02,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,5.170000e+02,5.170000e+02,5.170000e+02,5.170000e+02,517.000000,5.170000e+02,517.000000,5.170000e+02,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,5.170000e+02,517.000000,517.000000,517.000000,517.000000,517.000000,5.170000e+02,517.000000,517.000000,517.000000,5.170000e+02,517.000000,517.000000,5.170000e+02,517.000000,517.000000,5.170000e+02
mean,2003.636364,2.089547e+05,2.206118e+05,674.545455,36126.199420,30395.125725,924.512573,30076.762863,22490.825919,27171.984526,1.592582e+05,7.960044e+04,1.293543e+05,1.237953e+05,12170.659574,5.631221e+04,16676.495164,1.217315e+05,28353.756286,20494.481625,13925.001934,7933.154739,14995.176015,10938.114120,3571.415861,17917.295938,15599.056093,7253.504836,3134.249516,4487.280464,8036.324952,4248.317215,1.705797e+05,31938.903288,6436.085106,57918.019342,49055.841393,33891.785300,5.216601e+04,45028.549323,46441.029014,52072.808511,9.679434e+04,17743.234043,24256.222437,5.402252e+04,46718.632495,56225.628627,4.521384e+04
std,7.029787,4.624167e+05,3.826856e+05,2302.625137,39641.071927,31383.335725,1976.425141,50713.885207,55115.188066,72880.209807,3.500869e+05,2.377099e+05,2.645368e+05,2.693019e+05,28741.372277,1.299333e+05,60130.971710,2.612259e+05,77214.374003,45762.767792,32340.793591,19691.284355,36032.677694,25653.726883,8407.283309,43393.248533,38728.431263,21520.223172,7813.563107,12064.373384,21001.315207,12389.125730,3.735983e+05,75604.911477,16015.363735,127481.701386,107306.975824,76781.239412,1.294606e+05,100556.629663,100429.720195,115187.838999,2.083848e+05,44889.310791,54878.096613,1.522205e+05,98313.894250,124010.354123,1.208068e+05
min,1993.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00
25%,1997.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00
50%,2003.000000,1.066600e+04,1.000000e+05,0.000000,33684.470000,30000.000000,29.000000,17483.740000,366.000000,590.000000,6.730000e+03,2.609000e+03,5.301000e+03,4.842000e+03,100.000000,2.342000e+03,0.000000,5.095000e+03,731.000000,457.000000,318.000000,35.000000,350.000000,100.000000,0.000000,371.000000,319.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.794000e+03,404.000000,0.000000,1206.000000,2644.000000,1850.000000,1.352000e+03,1178.000000,1772.000000,1797.000000,3.962000e+03,266.000000,585.000000,9.560000e+02,1726.000000,1709.000000,1.548000e+03
75%,2010.000000,1.680520e+05,1.500000e+05,0.000000,67193.250000,60000.000000,587.000000,38807.280000,15711.000000,15877.000000,1.369490e+05,4.579100e+04,8.830500e+04,9.194300e+04,6470.000000,3.918200e+04,5192.000000,8.666900e+04,17703.000000,16355.000000,12002.000000,6227.000000,12854.000000,10210.000000,2848.000000,15223.000000,12745.000000,4112.000000,1987.000000,3526.000000,4572.000000,2618.000000,1.302680e+05,21310.000000,5017.000000,41234.000000,42986.000000,29917.000000,2.299800e+04,27106.000000,34617.000000,37542.000000,7.645500e+04,14164.000000,18968.000000,3.486500e+04,36493.000000,44780.000000,3.434700e+04
max,2015.000000,3.355678e+06,1.223166e+06,25000.000000,257851.200000,100000.000000,13432.000000,397375.060000,469649.000000,674394.000000,2.498144e+06,2.356928e+06,1.662362e+06,1.907867e+06,191373.000000,1.107422e+06,576918.000000,1.630920e+06,619478.000000,343052.000000,231426.000000,175123.000000,315784.000000,219465.000000,84421.000000,356514.000000,315930.000000,214792.000000,60377.000000,118123.000000,169954.000000,122602.000000,2.593450e+06,643160.000000,135503.000000,793888.000000,776574.000000,593001.000000,1.119969e+06,741284.000000,696562.000000,849298.000000,1.427662e+06,411183.000000,404438.000000,1.285030e+06,637806.000000,905374.000000,1.089982e+06

In [92]:
# Cheking for Null Valves in Dataset 
df.isnull().sum()

Year                                                             0
Demographics.Total                                               0
Education.Major                                                  0
Salaries.Highest                                                 0
Salaries.Lowest                                                  0
Salaries.Mean                                                    0
Salaries.Median                                                  0
Salaries.Quantity                                                0
Salaries.Standard Deviation                                      0
Demographics.Ethnicity.Asians                                    0
Demographics.Ethnicity.Minorities                                0
Demographics.Ethnicity.Whites                                    0
Demographics.Gender.Females                                      0
Demographics.Gender.Males                                        0
Education.Degrees.Bachelors                                      0
Education.Degrees.Doctorates                                     0
Education.Degrees.Masters                                        0
Education.Degrees.Professionals                                  0
Employment.Employer Type.Business/Industry                       0
Employment.Employer Type.Educational Institution                 0
Employment.Employer Type.Government                              0
Employment.Reason Working Outside Field.Career Change            0
Employment.Reason Working Outside Field.Family-related           0
Employment.Reason Working Outside Field.Job Location             0
Employment.Reason Working Outside Field.No Job Available         0
Employment.Reason Working Outside Field.Other                    0
Employment.Reason Working Outside Field.Pay/Promotion            0
Employment.Reason Working Outside Field.Working Conditions       0
Employment.Reason for Not Working.Family                         0
Employment.Reason for Not Working.Layoff                         0
Employment.Reason for Not Working.No Job Available               0
Employment.Reason for Not Working.No need/want                   0
Employment.Reason for Not Working.Student                        0
Employment.Status.Employed                                       0
Employment.Status.Not in Labor Force                             0
Employment.Status.Unemployed                                     0
Employment.Work Activity.Accounting/Finance/Contracts            0
Employment.Work Activity.Applied Research                        0
Employment.Work Activity.Basic Research                          0
Employment.Work Activity.Computer Applications                   0
Employment.Work Activity.Design                                  0
Employment.Work Activity.Development                             0
Employment.Work Activity.Human Resources                         0
Employment.Work Activity.Managing/Supervising People/Projects    0
Employment.Work Activity.Other                                   0
Employment.Work Activity.Productions/Operations/Maintenance      0
Employment.Work Activity.Professional Service                    0
Employment.Work Activity.Qualitity/Productivity Management       0
Employment.Work Activity.Sales, Purchasing, Marketing            0
Employment.Work Activity.Teaching                                0
dtype: int64

In [93]:
df.duplicated().sum()

np.int64(0)

In [94]:
# Counts Dataset Types 
df.dtypes

Year                                                               int64
Demographics.Total                                                 int64
Education.Major                                                      str
Salaries.Highest                                                   int64
Salaries.Lowest                                                    int64
Salaries.Mean                                                    float64
Salaries.Median                                                    int64
Salaries.Quantity                                                  int64
Salaries.Standard Deviation                                      float64
Demographics.Ethnicity.Asians                                      int64
Demographics.Ethnicity.Minorities                                  int64
Demographics.Ethnicity.Whites                                      int64
Demographics.Gender.Females                                        int64
Demographics.Gender.Males                                          int64
Education.Degrees.Bachelors                                        int64
Education.Degrees.Doctorates                                       int64
Education.Degrees.Masters                                          int64
Education.Degrees.Professionals                                    int64
Employment.Employer Type.Business/Industry                         int64
Employment.Employer Type.Educational Institution                   int64
Employment.Employer Type.Government                                int64
Employment.Reason Working Outside Field.Career Change              int64
Employment.Reason Working Outside Field.Family-related             int64
Employment.Reason Working Outside Field.Job Location               int64
Employment.Reason Working Outside Field.No Job Available           int64
Employment.Reason Working Outside Field.Other                      int64
Employment.Reason Working Outside Field.Pay/Promotion              int64
Employment.Reason Working Outside Field.Working Conditions         int64
Employment.Reason for Not Working.Family                           int64
Employment.Reason for Not Working.Layoff                           int64
Employment.Reason for Not Working.No Job Available                 int64
Employment.Reason for Not Working.No need/want                     int64
Employment.Reason for Not Working.Student                          int64
Employment.Status.Employed                                         int64
Employment.Status.Not in Labor Force                               int64
Employment.Status.Unemployed                                       int64
Employment.Work Activity.Accounting/Finance/Contracts              int64
Employment.Work Activity.Applied Research                          int64
Employment.Work Activity.Basic Research                            int64
Employment.Work Activity.Computer Applications                     int64
Employment.Work Activity.Design                                    int64
Employment.Work Activity.Development                               int64
Employment.Work Activity.Human Resources                           int64
Employment.Work Activity.Managing/Supervising People/Projects      int64
Employment.Work Activity.Other                                     int64
Employment.Work Activity.Productions/Operations/Maintenance        int64
Employment.Work Activity.Professional Service                      int64
Employment.Work Activity.Qualitity/Productivity Management         int64
Employment.Work Activity.Sales, Purchasing, Marketing              int64
Employment.Work Activity.Teaching                                  int64
dtype: object

In [95]:
# Counts DTYPES in Dataset 
df.dtypes.value_counts()

int64      47
float64     2
str         1
Name: count, dtype: int64

In [96]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
df.columns.tolist()

['Year',
 'Demographics.Total',
 'Education.Major',
 'Salaries.Highest',
 'Salaries.Lowest',
 'Salaries.Mean',
 'Salaries.Median',
 'Salaries.Quantity',
 'Salaries.Standard Deviation',
 'Demographics.Ethnicity.Asians',
 'Demographics.Ethnicity.Minorities',
 'Demographics.Ethnicity.Whites',
 'Demographics.Gender.Females',
 'Demographics.Gender.Males',
 'Education.Degrees.Bachelors',
 'Education.Degrees.Doctorates',
 'Education.Degrees.Masters',
 'Education.Degrees.Professionals',
 'Employment.Employer Type.Business/Industry',
 'Employment.Employer Type.Educational Institution',
 'Employment.Employer Type.Government',
 'Employment.Reason Working Outside Field.Career Change',
 'Employment.Reason Working Outside Field.Family-related',
 'Employment.Reason Working Outside Field.Job Location',
 'Employment.Reason Working Outside Field.No Job Available',
 'Employment.Reason Working Outside Field.Other',
 'Employment.Reason Working Outside Field.Pay/Promotion',
 'Employment.Reason Working Outside Field.Working Conditions',
 'Employment.Reason for Not Working.Family',
 'Employment.Reason for Not Working.Layoff',
 'Employment.Reason for Not Working.No Job Available',
 'Employment.Reason for Not Working.No need/want',
 'Employment.Reason for Not Working.Student',
 'Employment.Status.Employed',
 'Employment.Status.Not in Labor Force',
 'Employment.Status.Unemployed',
 'Employment.Work Activity.Accounting/Finance/Contracts',
 'Employment.Work Activity.Applied Research',
 'Employment.Work Activity.Basic Research',
 'Employment.Work Activity.Computer Applications',
 'Employment.Work Activity.Design',
 'Employment.Work Activity.Development',
 'Employment.Work Activity.Human Resources',
 'Employment.Work Activity.Managing/Supervising People/Projects',
 'Employment.Work Activity.Other',
 'Employment.Work Activity.Productions/Operations/Maintenance',
 'Employment.Work Activity.Professional Service',
 'Employment.Work Activity.Qualitity/Productivity Management',
 'Employment.Work Activity.Sales, Purchasing, Marketing',
 'Employment.Work Activity.Teaching']

In [97]:
df = df.drop(columns=[
    "Salaries.Mean",
    "Salaries.Median", "Demographics.Ethnicity.Minorities","Salaries.Quantity", "Salaries.Standard Deviation", "Employment.Employer Type.Business/Industry", "Employment.Employer Type.Government", "Employment.Reason Working Outside Field.Career Change", "Employment.Reason Working Outside Field.Career Change", "Employment.Reason Working Outside Field.Family-related","Employment.Reason Working Outside Field.Job Location", "Employment.Reason Working Outside Field.Other", "Employment.Reason Working Outside Field.Working Conditions", "Employment.Reason for Not Working.Family","Employment.Reason for Not Working.Layoff", "Employment.Reason for Not Working.No Job Available","Employment.Reason for Not Working.No need/want","Employment.Reason for Not Working.Student","Employment.Work Activity.Accounting/Finance/Contracts","Employment.Work Activity.Applied Research", "Employment.Work Activity.Basic Research","Employment.Work Activity.Computer Applications","Employment.Work Activity.Design","Employment.Work Activity.Development","Employment.Work Activity.Human Resources",
    "Employment.Work Activity.Managing/Supervising People/Projects","Employment.Work Activity.Other","Employment.Work Activity.Productions/Operations/Maintenance","Employment.Work Activity.Professional Service","Employment.Work Activity.Qualitity/Productivity Management","Employment.Work Activity.Sales, Purchasing, Marketing", "Employment.Work Activity.Teaching"
])

In [98]:
df.columns

Index(['Year', 'Demographics.Total', 'Education.Major', 'Salaries.Highest',
       'Salaries.Lowest', 'Demographics.Ethnicity.Asians',
       'Demographics.Ethnicity.Whites', 'Demographics.Gender.Females',
       'Demographics.Gender.Males', 'Education.Degrees.Bachelors',
       'Education.Degrees.Doctorates', 'Education.Degrees.Masters',
       'Education.Degrees.Professionals',
       'Employment.Employer Type.Educational Institution',
       'Employment.Reason Working Outside Field.No Job Available',
       'Employment.Reason Working Outside Field.Pay/Promotion',
       'Employment.Status.Employed', 'Employment.Status.Not in Labor Force',
       'Employment.Status.Unemployed'],
      dtype='str')

In [ ]:
df = df.rename(columns={
    'Year':'Graduation Year', 
    'Education.Major': 'Major', 
    'Salaries.Highest':'Highest Salary',
       'Salaries.Lowest':'Lowest Salary', 
       Demographics.Ethnicity.Asians':'Asian_Count',
       'Demographics.Ethnicity.Minorities':'Demographics.Ethnicity.Minorities', 'Demographics.Ethnicity.Whites':'Demographics.Ethnicity.Whites',
       'Demographics.Gender.Females':'Demographics.Gender.Females', 'Demographics.Gender.Males':'Demographics.Gender.Males',
       'Education.Degrees.Bachelors', 'Education.Degrees.Doctorates',
       'Education.Degrees.Masters', 'Education.Degrees.Professionals',
       'Employment.Employer Type.Educational Institution',
       'Employment.Reason Working Outside Field.No Job Available',
       'Employment.Reason Working Outside Field.Pay/Promotion',
       'Employment.Status.Employed', 'Employment.Status.Not in Labor Force',
       'Employment.Status.Unemployed'],
      dtype='str')
    
})

SyntaxError: unterminated string literal (detected at line 2) (2394038198.py, line 2)